# Indicate the version number
#:kivy 1.0.9

# Customize the SadFaceWidget that was declared in the .py file with the
# following attributes
<SadFaceWidget>
    size: 200, 200
    source: 'images/sad_face.png'

# Customize the HappyFaceWidget that was declared in the .py file with the
# following attributes
<HappyFaceWidget>
    size: 200, 200
    source: 'images/happy_face.png'

# Customize the RootWidget that was declared in the .py file
<RootWidget>

    # Add a label text field with the following attributes
    Label:
        font_size: 50
        center_x: root.width / 2
        top: root.top - 50
        text: 'How are you feeling today?'
        color: 0,0,0,1

    # Place the actual face widgets on the RootWidget and indicate their position
    SadFaceWidget:
        pos: ((root.width / 5) * 1) + (root.width / 28) , root.top - 500

    HappyFaceWidget:
        pos: ((root.width / 5) * 3) + (root.width / 28), root.top - 500
 
